name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build CMP186-WorkshopGitHubAction/CMP186-WorkshopGitHubAction.sln --no-restore
    - name: Test
      run: dotnet test CMP186-WorkshopGitHubAction/CMP186-WorkshopGitHubAction.sln --no-build --verbosity normal
    - name: Publish
      run: dotnet publish CMP186-WorkshopGitHubAction/CMP186-WorkshopGitHubAction.sln
